

ifeq ($(IDENTIFIER),kenzo@majorana)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC
        LDFLAGS=-L/home/kenzo/Codes/HswfQMC/lapack_lib
        FC=mpif90
endif

ifeq ($(IDENTIFIER),kenzo@crazydiamond)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC
        LDFLAGS=-L/Users/kenzo/Applications/HswfQMC/lapack_lib
        FC=mpif90-openmpi-gcc49
endif

