ifeq ($(IDENTIFIER),kenzo@majorana)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/storage/Codes/HswfQMC/lapack_lib -I/storage/Codes/HswfQMC/markuspline -L/storage/Codes/HswfQMC/markuspline
        FC=mpif90
endif

ifeq ($(IDENTIFIER),francesco086@Tesla)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/Users/francesco086/Applications/HswfQMC/lapack_lib -I/Users/francesco086/Applications/HswfQMC/markuspline -L/Users/francesco086/Applications/HswfQMC/markuspline
        FC=mpif90-openmpi-gcc49
endif

ifeq ($(IDENTIFIER),francesco086@Tesla.local)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/Users/francesco086/Applications/HswfQMC/lapack_lib -I/Users/francesco086/Applications/HswfQMC/markuspline -L/Users/francesco086/Applications/HswfQMC/markuspline
        FC=mpif90-openmpi-gcc49
endif

ifeq ($(IDENTIFIER),kenzo@roothan)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/home/kenzo/HswfQMC/lapack_lib -I/home/kenzo/HswfQMC/markuspline -L/home/kenzo/HswfQMC/markuspline
        FC=mpif90
endif

