ifeq ($(IDENTIFIER),kenzo@majorana)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/storage/Codes/HswfQMC/lapack_lib -I/storage/Codes/HswfQMC/markuspline -L/storage/Codes/HswfQMC/markuspline
        FC=mpif90
endif

ifeq ($(IDENTIFIER),francesco086@Tesla)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/Users/francesco086/Applications/HswfQMC/lapack_lib -I/Users/francesco086/Applications/HswfQMC/markuspline -L/Users/francesco086/Applications/HswfQMC/markuspline
        FC=mpif90-openmpi-gcc49
endif

ifeq ($(IDENTIFIER),francesco086@Tesla.local)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/Users/francesco086/Applications/HswfQMC/lapack_lib -I/Users/francesco086/Applications/HswfQMC/markuspline -L/Users/francesco086/Applications/HswfQMC/markuspline
        FC=mpif90-openmpi-gcc49
endif

ifeq ($(IDENTIFIER),jakessle@login02.mogon)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/home/jakessle/HswfQMC/lapack_lib -I/home/jakessle/HswfQMC/markuspline -L/home/jakessle/HswfQMC/markuspline
        FC=mpif90
endif

ifeq ($(IDENTIFIER),jakessle@jmbprow.home)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/Users/jakessle/AeroFS/TCM/Code/HswfQMC/lapack_lib -I/Users/jakessle/AeroFS/TCM/Code/HswfQMC/markuspline -L/Users/jakessle/AeroFS/TCM/Code/HswfQMC/markuspline
endif

ifeq ($(IDENTIFIER),kenzo@roothan)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/home/kenzo/HswfQMC/lapack_lib -I/home/kenzo/HswfQMC/markuspline -L/home/kenzo/HswfQMC/markuspline
        FC=mpif90
endif

ifeq ($(IDENTIFIER),jakessle@login01.mogon)
        EXEC=$(EXEC1)
        LIBS=-llapackHswfQMC -lblasHswfQMC -lmarkusplineHswfQMC
        LDFLAGS=-L/home/jakessle/HswfQMC/lapack_lib -I/home/jakessle/HswfQMC/markuspline -L/home/jakessle/HswfQMC/markuspline
        FC=mpif90
endif

ifeq ($(IDENTIFIER),hpb015@juqueen1.zam.kfa-juelich.de)
        EXEC=$(EXEC1)
        LIBS=-lmarkusplineHswfQMC -llapack -lesslbg
        LDFLAGS=-L$(LAPACK_LIB) -L/bgsys/local/lib -I/homea/hpb01/hpb015/HswfQMC/markuspline -L/homea/hpb01/hpb015/HswfQMC/markuspline
        FC=mpixlf2003_r
endif

ifeq ($(IDENTIFIER),hpb015@juqueen2.zam.kfa-juelich.de)
        EXEC=$(EXEC1)
        LIBS=-lmarkusplineHswfQMC -llapack -lesslbg
        LDFLAGS=-L$(LAPACK_LIB) -L/bgsys/local/lib -I/homea/hpb01/hpb015/HswfQMC/markuspline -L/homea/hpb01/hpb015/HswfQMC/markuspline
        FC=mpixlf2003_r
endif

ifeq ($(IDENTIFIER),hpb015@juqueen3.zam.kfa-juelich.de)
        EXEC=$(EXEC1)
        LIBS=-lmarkusplineHswfQMC -llapack -lesslbg
        LDFLAGS=-L$(LAPACK_LIB) -L/bgsys/local/lib -I/homea/hpb01/hpb015/HswfQMC/markuspline -L/homea/hpb01/hpb015/HswfQMC/markuspline
        FC=mpixlf2003_r
endif

